### ISSUE TITLE
Samarux compiling enviroment

### ISSUE THREAD

**Issue by kenmartin-unix** [MiguelVis/samarux#2]
Miguel,

From what I have seen is samarux designed to be complied under Windows?

If so what additional software do I need? Compilers?

Can it be compiled under Linux?

After compiling under Windows/Linux can it then be used on CP/M?

Thanks
Ken

**Comment by MiguelVis** [comment]
Hi @kenmartin-unix 

The only Windows tool I use is CPM.EXE, a CP/M emulator, in order to execute the other CP/M native tools: MESCC, CCOPT, ZSM and HEXTOCOM, all of them you will find ay my GitHub repositories.

So, I don't see any problem compiling SamaruX in other OS environment, if you find a CP/M 2 emulator for it.
